#import "./MessageFields.frag.gql"
#import "./UserFields.frag.gql"

query FindUserByEmail($email : String) {
  user(email: $email) {
    ...UserFields

    messages {
      ...MessageFields
    }
  }
}